
test:
  storage: !ruby/sym file

development:
  storage: !ruby/sym file

production:
  storage: !ruby/sym right_s3
  s3_access_key_id: XYZ
  s3_secret_access_key: XYZ
  s3_bucket: assets.example.com
  s3_cnamed: true

